builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
brews:
  - name: lukso-cli
    homepage: https://github.com/meta-bot/homebrew-tools
    tap:
      owner: meta-bot
      name: homebrew-tools
