builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
brews:
  - name: lukso-cli
    homepage: https://github.com/lukso-network/homebrew-tools
    tap:
      owner: lukso-network
      name: homebrew-tools
      branch: main
      token: "{{ .ENV.TAP_GITHUB_TOKEN }}"
