builds:
  - goos:
      - linux
      - darwin
    env:
      - GIT_TOKEN=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
    goarch:
      - amd64
      - arm64
brews:
  - name: lukso-cli
    homepage: https://github.com/meta-bot/homebrew-tools
    tap:
      owner: meta-bot
      name: homebrew-tools
      token: ${{ .Env.GIT_TOKEN }}
